---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
  namespace: test
spec:
  selector:
    matchLabels:
      app: member
  replicas: 1
  template:
    metadata:
      labels:
        app: member
    spec:
      imagePullSecrets:
        - name: ecr-image-pull-secret
      containers:
      - image: 382942022480.dkr.ecr.us-east-1.amazonaws.com/member:**TAG**
        name: member
        ports:
        - name: memberport
          containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: member
  namespace: test
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: memberport
  type: ClusterIP
  selector:
    app: member
---
apiVersion: v1
kind: Service
metadata:
  name: member-postgres-service
  namespace: test
spec:
  selector:
    app: member-postgres
  ports:
    - name: member-postgres
      port: 5432
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-postgres
  namespace: test
spec:
  selector:
    matchLabels:
      app: member-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: member-postgres
    spec:
      containers:
        - name: member-postgres
          image: postgres:12.4
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: member-postgres-data
              mountPath: /var/lib/member/postgresql/data
      volumes:
        - name: member-postgres-data
          emptyDir: {}